# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.88122195 0.2804132  0.31914229]
  [0.58389109 0.6829364  0.49420931]
  [0.65246992 0.52529588 0.75803452]]

 [[0.25775801 0.74083241 0.0912407 ]
  [0.94777873 0.00845966 0.57663892]
  [0.60770193 0.88386491 0.6064411 ]]

 [[0.48520774 0.19171588 0.03512947]
  [0.56389958 0.53441523 0.81062926]
  [0.27164494 0.59719131 0.03295436]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.82215573 0.47726736 0.55908334 0.07125948 0.97495205]
 [0.22544437 0.78377327 0.87924252 0.44677491 0.01966772]
 [0.24140961 0.82523608 0.67704037 0.0689003  0.70983619]
 [0.78031484 0.70111309 0.71717353 0.56533516 0.44137809]
 [0.48046194 0.08624064 0.49852537 0.54388101 0.84870829]]
After normalization:
[[0.84005148 0.47901931 0.564665   0.05400671 1.        ]
 [0.2154088  0.79987238 0.89981043 0.44709954 0.        ]
 [0.23212135 0.84327601 0.68814344 0.05153709 0.72247439]
 [0.79625206 0.71334298 0.7301552  0.57120945 0.4414501 ]
 [0.48236343 0.06968912 0.50127238 0.54875106 0.86784693]]


# 5.  How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 0 1 0 1]
Second array:
[1 1 0 0 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.82582965 0.63801012 0.3197276  0.46902308 0.09451461 0.28594618
 0.89470058 0.2029478  0.67991825 0.56678639]
Maximum value replaced by -1:
[ 0.82582965  0.63801012  0.3197276   0.46902308  0.09451461  0.28594618
 -1.          0.2029478   0.67991825  0.56678639]


# 9. How to print all the values of an array?

In [10]:
import numpy as np
np.set_printoptions(threshold=1)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [11]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.64373231 0.2662835  0.62890395 ... 0.23857288 0.95527815 0.9897869 ]
 [0.23541296 0.98799187 0.69279912 ... 0.99423    0.77719688 0.53005015]
 [0.44094015 0.66994272 0.87817629 ... 0.79405371 0.7522722  0.7990692 ]
 [0.02401263 0.7106348  0.83440266 ... 0.07374822 0.62944363 0.23905026]
 [0.6785417  0.67237845 0.07445029 ... 0.15934585 0.86382623 0.40117023]]

Subtract the mean of each row of the said matrix:

[[ 0.04830607 -0.32914274  0.03347771 ... -0.35685336  0.35985191
   0.39436066]
 [-0.32313379  0.42944512  0.13425237 ...  0.43568325  0.21865014
  -0.0284966 ]
 [-0.15345972  0.07554286  0.28377643 ...  0.19965384  0.15787234
   0.20466934]
 [-0.31698431  0.36963787  0.49340572 ... -0.26724871  0.28844669
  -0.10194668]
 [ 0.21895439  0.21279114 -0.38513702 ... -0.30024145  0.40423892
  -0.05841708]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 2. 2. ... 3. 1. 1.]


# 12.How to get the diagonal of a dot product?

In [13]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([ 46,  81, 154])

# 13.How to find the most frequent value in an array?

In [14]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[8 5 6 ... 6 6 9]
rank: 4


# 14.How to get the n largest values of an array

In [15]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9996 9998 9997 9995]


# 15.How to create a record array from a regular array?

In [16]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')